GEMINI_API_KEY = "AIzaSyCX4uRPafM1IL6azZeTb8-OTqZcReVZrnE"
ROBOFLOW_API_KEY = "9Ir1ENQKiU8pasKqMi25" # Your Roboflow API Key
ROBOFLOW_MODEL_ID = "attempt/1" # Your Roboflow Model ID (workspace/project/version or project/version)
ROBOFLOW_API_URL = "https://detect.roboflow.com" # Or serverless if that's what you used